### PR TITLE
Check if other people can push

### PR DESCRIPTION
**Pull request by joy-rosie**
Hello,

Can someone make a minor edit to the repository and push to master or create a pull request?

I need to check if someone other than me can do this after changing from travis-ci to github actions

### CODE REVIEW

**Comment by datapythonista** [comment]
I can merge this, and I can push. Why shouldn't people with permissions not be able to?

**Comment by joy-rosie** [comment]
> I can merge this, and I can push. Why shouldn't people with permissions not be able to?

Sorry, what I meant is if you can create your own pull request with a small change and I would like to test if we can push that. 

Previously, because of the setup with travis and the git ssh key, it seemed to only be able to push when it was my account. Now that should not be a problem and just need to check that

**Comment by datapythonista** [comment]
I opened #35

**Comment by joy-rosie** [comment]
That has worked, thanks a lot!

**Pull request closed without merging**
